
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhkxsaozetijdfejaome.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhoa3hzYW96ZXRpamRmZWphb21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwODc0ODcsImV4cCI6MjA1NjY2MzQ4N30.smhix2ps4UMDnZIPotWABv2dxdmD4AJ129uUBm4ZU_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    // Enable debug logging in development
    global: {
      fetch: (...args) => {
        // Log all fetch requests in development
        if (process.env.NODE_ENV !== 'production') {
          console.log('Supabase fetch:', args[0]);
        }
        // @ts-ignore
        return fetch(...args);
      }
    },
  }
);
